package com.fieldbook.shared.preferences

object PreferenceKeys {
    const val BRAPI_ENABLED = "BRAPI_ENABLED"
    const val BRAPI_BASE_URL = "BRAPI_BASE_URL"
    const val BRAPI_OIDC_URL = "BRAPI_OIDC_URL"
    const val BRAPI_OIDC_FLOW = "BRAPI_OIDC_FLOW"
    const val BRAPI_OIDC_CLIENT_ID = "BRAPI_OIDC_CLIENT_ID"
    const val BRAPI_OIDC_SCOPE = "BRAPI_OIDC_SCOPE"
    const val BRAPI_EXPLICIT_OIDC_URL = "BRAPI_EXPLICIT_OIDC_URL"
    const val BRAPI_TOKEN = "BRAPI_TOKEN"
    const val BRAPI_VERSION = "BRAPI_VERSION"
    const val BRAPI_PAGE_SIZE = "BRAPI_PAGE_SIZE"
    const val BRAPI_TIMEOUT = "BRAPI_TIMEOUT"
    const val BRAPI_CHUNK_SIZE = "BRAPI_CHUNK_SIZE"
    const val BRAPI_DISPLAY_NAME = "BRAPI_DISPLAY_NAME"
    const val BRAPI_INVALIDATE_CACHE_INTERVAL = "BRAPI_CACHE_INVALIDATE_INTERVAL"
    const val LABELVAL_CUSTOMIZE = "LABELVAL_CUSTOMIZE"

    const val IMPORT_SOURCE_DEFAULT = "IMPORT_SOURCE_DEFAULT"
    const val EXPORT_SOURCE_DEFAULT = "EXPORT_SOURCE_DEFAULT"
}
