name: 🐛 Bug Report
description: I think I've discovered a bug or other issue.
type: "bug"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe your issue in as much detail as possible. For example: What happened? What did you expect to happen?
      placeholder: Description
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: |
        What should Field Book be doing differently?

  - type: input
    id: version
    attributes:
      label: Field Book version
      description: Check the About page in the app.
      placeholder: ex. 5.4.10
