services:
  brapi-light:
    build:
      context: ../brapi-light
    ports:
      - "38000:8000"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////data/brapi.db
    restart: unless-stopped
