apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'com.google.devtools.ksp'
apply plugin: "org.jetbrains.kotlin.plugin.serialization"

android {
    namespace "org.phenoapps.labelprint"
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 36
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation "androidx.core:core-ktx:1.17.0"
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    
    // Compose
    implementation platform('androidx.compose:compose-bom:2025.11.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-compose:1.11.0'
    implementation "androidx.compose.material:material-icons-extended:1.7.8"

    // ZXing for Barcodes/QR
    implementation 'com.google.zxing:core:3.5.3'

    // Serialization
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

    // Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0"

    // Dagger Hilt (optional but helpful if other apps use it)
    implementation "com.google.dagger:hilt-android:2.56.2"
    ksp "com.google.dagger:hilt-compiler:2.56.2"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
